from pydantic import BaseModel, Field
from typing import List, Literal, Optional, Any, Dict

class QuestionPlan(BaseModel):
    """
    Represents the list of question blueprints generated by the Planner.
    Each string in the list is a detailed blueprint.
    """
    questions: List[str]

class QuestionLLM(BaseModel):
    """Represents a single UPSC Prelims question generated by the LLM (English)."""
    question: str = Field(..., description="The complete text of the question.")
    options: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D)."
    )
    answer: Literal["A", "B", "C", "D"] = Field(
        ...,
        description="The letter corresponding to the correct answer option."
    )
    explanation: str = Field(
        ...,
        description="A concise explanation (3-5 sentences) of why the correct answer is right and key distractors are wrong."
    )

class QuestionLLMHindi(BaseModel):
    """Represents a single UPSC Prelims question translated to Hindi."""
    question: str = Field(..., description="The complete text of the question in Hindi Language.")
    options: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D) in Hindi Language."
    )
    answer: Literal["A", "B", "C", "D"] = Field(
        ..., 
        description="The letter corresponding to the correct answer option."
    )

class Question(BaseModel):
    """Represents a final processed UPSC Prelims question with both English and Hindi."""
    id: int = Field(..., description="Unique ID for the question (Display ID).")
    db_uuid: Optional[str] = Field(None, description="Database UUID for existing questions.")
    question_number: int = Field(..., description="Sequential number of the question in the test.")
    question_english: str = Field(..., description="The complete text of the question.")
    options_english: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D). in English."
    )
    question_hindi: str = Field(..., description="The complete text of the question in Hindi.")
    options_hindi: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D). in Hindi."
    )
    answer: Literal["A", "B", "C", "D"] = Field(
        ..., 
        description="The letter corresponding to the correct answer option."
    )
    question_blueprint: Optional[str] = Field(None, description="The blueprint used to generate this question.")
    subject: Optional[str] = Field(None, description="The subject of the question (mapped to CSV).")
    topic: Optional[str] = Field(None, description="The topic within the subject.")
    subtopic: Optional[str] = Field(None, description="The subtopic within the topic.")
    month: Optional[int] = Field(None, description="Month (1-12) (for PYQ questions).")
    year: Optional[int] = Field(None, description="Year (for PYQ questions).")
    test_type: Optional[str] = Field(None, description="Test Type: Comma-separated list of test types (Test Series, Daily Challenge, etc.)")
    prone_to_silly_mistakes: Optional[bool] = Field(None, description="Whether this question is prone to silly mistakes.")
    pattern: Optional[str] = Field(None, description="Question pattern/type.")
    difficulty: Optional[float] = Field(None, description="Difficulty level on 1-5 scale (2=Easy, 3=Moderate, 4=Difficult).")
    explanation: Optional[str] = Field(None, description="Explanation of the correct answer.")
    content_type: Optional[str] = Field(None, description="Content type: Static or Current Affairs.")
    user_feedback: Optional[str] = Field(None, description="User feedback/reason for selection/rejection.")
    is_selected: bool = Field(False, description="Whether the question is selected by the user.")
    is_rejected: bool = Field(False, description="Whether the question is rejected by the user.")

class TestPaper(BaseModel):
    """Represents the complete UPSC Prelims Test paper."""
    questions: List[Question]
