from pydantic import BaseModel, Field
from typing import List, Literal, Optional, Any, Dict

class QuestionPlan(BaseModel):
    """
    Represents the list of question blueprints generated by the Planner.
    Each string in the list is a detailed blueprint.
    """
    questions: List[str]

class QuestionLLM(BaseModel):
    """Represents a single UPSC Prelims question generated by the LLM (English)."""
    question: str = Field(..., description="The complete text of the question.")
    options: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D)."
    )
    answer: Literal["A", "B", "C", "D"] = Field(
        ..., 
        description="The letter corresponding to the correct answer option."
    )

class QuestionLLMHindi(BaseModel):
    """Represents a single UPSC Prelims question translated to Hindi."""
    question: str = Field(..., description="The complete text of the question in Hindi Language.")
    options: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D) in Hindi Language."
    )
    answer: Literal["A", "B", "C", "D"] = Field(
        ..., 
        description="The letter corresponding to the correct answer option."
    )

class Question(BaseModel):
    """Represents a final processed UPSC Prelims question with both English and Hindi."""
    id: int = Field(..., description="Unique ID for the question (Display ID).")
    db_uuid: Optional[str] = Field(None, description="Database UUID for existing questions.")
    question_number: int = Field(..., description="Sequential number of the question in the test.")
    question_english: str = Field(..., description="The complete text of the question.")
    options_english: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D). in English."
    )
    question_hindi: str = Field(..., description="The complete text of the question in Hindi.")
    options_hindi: List[str] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="A list of exactly four multiple-choice options (A, B, C, D). in Hindi."
    )
    answer: Literal["A", "B", "C", "D"] = Field(
        ..., 
        description="The letter corresponding to the correct answer option."
    )
    question_blueprint: Optional[str] = Field(None, description="The blueprint used to generate this question.")
    subject: Optional[str] = Field(None, description="The subject or topic of the question.")
    user_feedback: Optional[str] = Field(None, description="User feedback/reason for selection/rejection.")
    is_selected: bool = Field(False, description="Whether the question is selected by the user.")
    is_rejected: bool = Field(False, description="Whether the question is rejected by the user.")

class TestPaper(BaseModel):
    """Represents the complete UPSC Prelims Test paper."""
    questions: List[Question]
